# Generated by Django 5.2.4 on 2025-08-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='event_asset/default_image.jpg', null=True, upload_to='event_asset'),
        ),
    ]
